### ISSUE TITLE
It doesn't warn about locked accounts

### ISSUE THREAD

**Issue by yarda** [Lacro59/playnite-indiegala-plugin#13]
It seems Indiegala accounts locks quite often (e.g. when your IP is changed). Then upon locking if you log-in, it shows "account locked, enter unlock code" and the unlock code is simultaneously send to your e-mail address.

Unfortunately, it seems the plugin doesn't handle this and it only shows there are no new items on your account, log:
```
28-08 01:30:18.167|INFO|IndiegalaAccountClient:IndiegalaLibrary - User is connected
28-08 01:30:18.168|INFO|IndiegalaAccountClient:IndiegalaLibrary - Get on https://www.indiegala.com/library/showcase/1
28-08 01:30:27.755|WARN|IndiegalaAccountClient:IndiegalaLibrary - No showcase data
28-08 01:30:27.756|INFO|IndiegalaAccountClient:IndiegalaLibrary - Get on https://www.indiegala.com/library/bundle/1
28-08 01:30:37.986|WARN|IndiegalaAccountClient:IndiegalaLibrary - No bundle data
28-08 01:30:37.986|INFO|IndiegalaAccountClient:IndiegalaLibrary - Get on https://www.indiegala.com/library/store/1
28-08 01:30:50.782|WARN|IndiegalaAccountClient:IndiegalaLibrary - No store data
28-08 01:30:50.784|INFO|IndiegalaLibrary:IndiegalaLibrary - Added: 0 - Already added: 0
```

The problem can be resolved by unlocking the account from the browser. But I think the plugin should at least log, that the account is locked or better it should display the error/warning message in the UI, or at best it should open window and allow user to unlock the account.

**Comment by yarda** [comment]
Hmm, it seems there #8, but it didnt' work for me with the v1.4.1.

**Comment by Lacro59** [comment]
Can you try with the v2.0.1?

**Comment by yarda** [comment]
It correctly detected locked account, thanks, closing.
