### ISSUE TITLE
"Dead Hungry Diner" free game not imported

### ISSUE THREAD

**Issue by ivanbraidi** [Lacro59/playnite-indiegala-plugin#22]
The plugin works well with all the other freebies of the Indiegala library, except for this one:

Dead Hungry Diner (https://freebies.indiegala.com/dead-hungry-diner)

Don't know what's wrong with it, but I think that this issue could hide something deeper to investigate.

**Comment by ivanbraidi** [comment]
Problem persisting with all the freebies. It was working correctly before so it seems that something broke with the last update.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by ivanbraidi** [comment]
Hi there!

Just tried with v2.0.2 and I get this error:

![indiegala_error](https://user-images.githubusercontent.com/5060778/143485751-0e662564-fb43-4f26-a699-aa3d73c16e9e.jpg)

It's clearly related with the other issue (unblocking codes sent via email) that I saw you closed, but it's not solved at all.

Let me know if you need other details.

here is the log:
[playnite.log](https://github.com/Lacro59/playnite-indiegala-plugin/files/7604741/playnite.log)

**Comment by ivanbraidi** [comment]
A quick update: after unblocking my profile with the code sent via email (done in the browser on the indiegala site), I run a forced Indiegala library update and this time the plugin worked correctly and imported all the missing games. So it seems that this issue is solved, but is not solved the multiple verification codes email sending and the indiegala account blocking.

Hope this could be of some help! :)

**Comment by Lacro59** [comment]
Login system must be changed.
