### ISSUE TITLE
Plugin does not recognize installed games and keeps resetting installed status

### ISSUE THREAD

**Issue by claudiombsilva** [Lacro59/playnite-indiegala-plugin#26]
Plugin version: 2.0.2

Issues:

1. When importing new games into Playnite that were already installed on disk by the IndieGala client, the installation folder is not detected, even though the library base folder setting for the plugin is correctly configured. So, games are always imported as "not installed".
2. After an update, all my IndieGala games become marked as not installed.

Further explanations:

1. It doesn't matter if I select "Use client" or not.
2. If I manually input each game's installation folder and enable the "installed" checkbox, when I update the IndieGala library, all games become marked as not installed again.  
The configured installation folder is not reset, though.

Even if you do not solve the folder detection bug, could you please add a simple check to prevent the plugin from resetting the "installed" flag?  
The check could be as simple as checking whether the game's installation folder is already set on the game's properties and if it is marked as installed. If true, the plugin would not reset the "installed" status.  
It should be a small change and quick to implement, but it would make a big difference, as that way, at least I can configure the games manually, otherwise its working in vain, as games keep getting marked as not installed on each library update.

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by claudiombsilva** [comment]
Sure:

```
08-12 19:20:59.884|INFO |IndiegalaLibrary#IndiegalaAccountClient:User is connected without client
08-12 19:20:59.884|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/1
08-12 19:21:12.474|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/2
08-12 19:21:15.569|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/3
08-12 19:21:21.559|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
08-12 19:21:21.559|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/bundle/1
08-12 19:21:27.316|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
08-12 19:21:27.316|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/store/1
08-12 19:21:32.264|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
08-12 19:21:32.264|INFO |IndiegalaLibrary#IndiegalaLibrary:Added: 0 - Already added: 11
```

The following is the content of the plugin's `config.json`:

```
{
  "UseClient": false,
  "ImageSelectionPriority": 2,
  "SelectOnlyWithoutStoreUrl": true,
  "InstallPath": "J:\\IndieGala"
}
```

What is interesting is that I installed one game directly from within Playnite and that game is correctly marked as installed, even after a library update.
The other games were installed with the IndieGala official client, outside of Playnite. They are always reset to "not installed" status.

**Comment by Lacro59** [comment]
Your config.json indicates that you have not checked the use of the client.
Can you try after check this options?

In addition, do you have add manually the play action for the game installed with client?

**Comment by claudiombsilva** [comment]
As I said on my original post, "It doesn't matter if I select "Use client" or not."

As for your question "do you have add manually the play action for the game installed with client?", I'm not sure I understand what you mean.
Are you asking if I manually configured the installation folder for each IndieGala game on Playnite?
Yes I did, as the IndieGala plugin did not detect the installation folders. It seems to have no idea where the games are installed. But the IGClient knows.
The plugin always marks the games as not installed, but does not change the configured installation folder (on Playnite) for each one. If it's empty, it remains empty, if it's set, it remains set. The plugin only resets the "installed" checkbox.

**Comment by claudiombsilva** [comment]
Ah, I figured out what you mean with "play action".
All IndieGala games that were imported by the plugin had just one action, and it was called "Download". They had no play action, as you can see in the screenshot below:

![Capture 1](https://user-images.githubusercontent.com/65917838/145725526-8fa725de-4f74-48ae-a3bf-3ee17fe4940f.png)

If I manually add a play action like this:

![Capture 2](https://user-images.githubusercontent.com/65917838/145725546-19d40c8f-3a29-4719-bb8b-ed7f0910ac00.png)

Then the game no longer becomes marked as not installed whenever I update my IndieGala library.

So, now that I know this, I manually configured play actions for all my games and they remain marked as installed when I update my libraries,

BUT the original problem with the plugin remains:
Games installed with the IndieGala client are not be configured correctly when imported with this plugin.
This is how a newly imported game is configured:
 
![Capture 0](https://user-images.githubusercontent.com/65917838/145726645-c632aa61-2706-4d9b-a817-363530351ff1.png)

And, of course, as you can see on the first screenshot, the game will have only a Download action configured.

Note: If I install the game from withing Playnite, then it is configured correctly.

This is the content of `extensions.log` after I imported my latest game:

```
12-12 19:19:38.096|INFO |IndiegalaLibrary#IndiegalaAccountClient:User is connected without client
12-12 19:19:38.154|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/1
12-12 19:19:54.877|ERROR|IndiegalaLibrary#Common:Error on GetOwnedGamesShowcase()|D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs|1065
System.ArgumentException: Caracteres inválidos no caminho.
   em System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   em System.IO.Path.Combine(String path1, String path2)
   em IndiegalaLibrary.Services.IndiegalaAccountClient.CheckIsInstalled(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings, GameMetadata gameMetadata) em D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:line 1152
   em IndiegalaLibrary.Services.IndiegalaAccountClient.GetOwnedGamesShowcase(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings) em D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:line 1065
12-12 19:19:54.877|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/2
12-12 19:19:59.836|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/3
12-12 19:20:02.355|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
12-12 19:20:02.355|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/bundle/1
12-12 19:20:08.156|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
12-12 19:20:08.156|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/store/1
12-12 19:20:10.072|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
12-12 19:20:10.086|INFO |IndiegalaLibrary#IndiegalaLibrary:Added: 1 - Already added: 11
```

This time there is an error message, but I don't know if it is related to the problem.

The plugin is configured this way:

![Capture 3](https://user-images.githubusercontent.com/65917838/145726729-017f3c8a-1de2-4dfc-a1df-f646c7eddc49.png)

The strange thing is that I have the plugin configured to "Use client" and I have the client installed. But in the log, the plugin says "User is connected without client".

**Comment by forenta** [comment]
Same issue here. Turned on client-usage to give it a try without success. Every game in the library detected, but none as installed.

We both have our IG library on an unusual drive letter (J in your, T in my case). Plus in both cases the plugin tries to get access to a file named `IndiegalaAccountClient.cs` on `D:\GitHub\Lacro59\playnite-indiegala-plugin` - a folder which doesn't exist at least in my case. Unlike the other libraries, the IG-extension does not appear in my `%PROGRAMFILES%\Playnite\Extensions`.

config.json:
`{
  "UseClient": true,
  "ImageSelectionPriority": 2,
  "SelectOnlyWithoutStoreUrl": true,
  "InstallPath": "T:\\IndieGala"
}`

extensions.log:
`09-01 20:51:50.296|ERROR|IndiegalaLibrary#Common:Error on GetOwnedGamesShowcase()|D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs|1065
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IndiegalaLibrary.Services.IndiegalaAccountClient.CheckIsInstalled(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings, GameMetadata gameMetadata) in D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:Zeile 1148.
   bei IndiegalaLibrary.Services.IndiegalaAccountClient.GetOwnedGamesShowcase(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings) in D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:Zeile 1065.
09-01 20:51:50.296|ERROR|IndiegalaLibrary#Common:Error on GetOwnedGamesShowcase()|D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs|1065
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IndiegalaLibrary.Services.IndiegalaAccountClient.CheckIsInstalled(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings, GameMetadata gameMetadata) in D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:Zeile 1148.
   bei IndiegalaLibrary.Services.IndiegalaAccountClient.GetOwnedGamesShowcase(IndiegalaLibrary Plugin, IndiegalaLibrarySettingsViewModel PluginSettings) in D:\GitHub\Lacro59\playnite-indiegala-plugin\source\Services\IndiegalaAccountClient.cs:Zeile 1065.
09-01 20:51:50.296|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/showcase/3
09-01 20:51:53.569|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
09-01 20:51:53.569|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/bundle/1
09-01 20:51:56.629|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
09-01 20:51:56.629|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/store/1
09-01 20:52:04.062|INFO |IndiegalaLibrary#IndiegalaAccountClient:Get on https://www.indiegala.com/library/store/2
09-01 20:52:16.373|INFO |IndiegalaLibrary#IndiegalaAccountClient:End list
09-01 20:52:16.373|INFO |IndiegalaLibrary#IndiegalaLibrary:Added: 1 - Already added: 9`

**Comment by ArtexJay** [comment]
this is a plugin breaking issue. It doesn't show, know or see when or if the game is installed.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-indiegala-plugin/commit/7dbbd8a1e62f938772d96057157ceb70bb328deb
