### ISSUE TITLE
Adding support to redirect recaptcha

### ISSUE THREAD

**Issue by ATNewHope** [Lacro59/playnite-indiegala-plugin#28]
Recaptcha is required to sign in indiegala.
However, [www.google.com/recaptcha/](url) is not accessible in China, so people usually redirect the url to [recaptcha.net/recaptcha/](url) .
To redirect, I can use Header Editor or Gooreplacer for browser like Firefox, Edge, Chrome, etc, but I can't use this on Playnite extension.
So, could you please consider adding support to redirect www.google.com/recaptcha/ to recaptcha.net/recaptcha/ ?
Thank you.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-indiegala-plugin/commit/13536217457ee0e30b7b4795fc64129b8f645506
