### ISSUE TITLE
Bundle Games not being fetched

### ISSUE THREAD

**Issue by ArtexJay** [Lacro59/playnite-indiegala-plugin#4]
I have recently bought a bundle game on indiegala and they are not being fetched by the plug in. They are indiegala  downloadable games, does not have steam key.

**Comment by Lacro59** [comment]
I haven't bundle on Indiegala yet.
By consequent, I can't see the page structure for add it.

**Comment by ArtexJay** [comment]
> I haven't bundle on Indiegala yet.
> By consequent, I can't see the page structure for add it.

That's too bad, well for me that's the only thing that's missing at this time. Otherwise it would be a completely finalized integration for Indiegala.

**Comment by ohadschn** [comment]
Would be interested in this as well!
@Lacro59 I've made a small contribution via your PayPal account that should cover a bundle of your choosing if you'd like :)

**Comment by Lacro59** [comment]
> Would be interested in this as well!
> @Lacro59 I've made a small contribution via your PayPal account that should cover a bundle of your choosing if you'd like :)

Thank you very much @ohadschn 
I will find and get an Indiegala game to finalize the plugin.

**Comment by ohadschn** [comment]
Well at the time of writing I see 3 active bundles, either one would do I think:
1. https://www.indiegala.com/bundle/beyond-infinity-steam-bundle
1. https://www.indiegala.com/bundle/nom-war-steam-bundle
1. https://www.indiegala.com/bundle/alien-cat-games-bundle

**Comment by Lacro59** [comment]
The release 1.1 add the support for Bunlde & Store.
