### ISSUE TITLE
Plugin Unable to Detect Installed Client Location

### ISSUE THREAD

**Issue by ArtexJay** [Lacro59/playnite-indiegala-plugin#40]
![image](https://user-images.githubusercontent.com/32932497/219757863-50e9fe0e-c21a-4037-8192-f4b0ed0d2bdf.png)

![image](https://user-images.githubusercontent.com/32932497/219762630-8b3a79ec-e358-425d-b131-309d24435d11.png)

As you can see the plugin is incapable of auto-detecting the install location of Indigala. In addition it's faded out so I am unable to specify it's location.
Due to this the install button in playnite for indigala games is useless, returns an error that it doesn't know where indigala is installed. 
I've been unable to install via the install button for indiegala games be it in library or bundle collection.

**Comment by ArtexJay** [comment]
In addition rather than just saying "Checking" or "Logged in" it now has <!LOCStatusHere>

**Comment by ArtexJay** [comment]
Fixed it by unticking "Use Client" and specifying a new download/install folder for the plugin.

Apparently it will be unable to download or install games if it's ticked. 
What's the point of "Use Client" if it's pretty much useless and will complain that no install directory is found even when specified before ticking it.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-indiegala-plugin/commit/7dbbd8a1e62f938772d96057157ceb70bb328deb
