### ISSUE TITLE
Malformed URL not allowing metadata download

### ISSUE THREAD

**Issue by coreyemtp** [Lacro59/playnite-indiegala-plugin#43]
As stated in the header, when the app attempts to download metadata from IndieGala, it fails with a malformed URL. I've attached an image. Playnite v10.14.

Thanks!

![Screenshot (8)](https://user-images.githubusercontent.com/59758878/231851090-679e9634-c1ca-450c-91ed-e6629ef99074.png)

**Comment by tynansdtm** [comment]
Same issue here.

![image](https://github.com/Lacro59/playnite-indiegala-plugin/assets/19171387/3d17947e-d325-4999-b422-1a96dd80bf87)

**Comment by lucslav** [comment]
I'm getting the same problem

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-indiegala-plugin/commit/c569a9b23d71cc00946c56b8a4aa64051bc9c321
