### ISSUE TITLE
Translations not working for login status

### ISSUE THREAD

**Issue by Mrxx99** [Lacro59/playnite-indiegala-plugin#44]
Here you can see, the login status is not translated, only the ID is showing:
![grafik](https://github.com/Lacro59/playnite-indiegala-plugin/assets/33566379/e8e8445e-bcce-4ace-b6f2-d89c891d2606)
![grafik](https://github.com/Lacro59/playnite-indiegala-plugin/assets/33566379/5e9cf86b-28ca-4a11-b787-5c471a805fad)
![grafik](https://github.com/Lacro59/playnite-indiegala-plugin/assets/33566379/1999fd5e-e016-4464-a607-bef8f01304c3)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-indiegala-plugin/commit/5425ab25d8f1e98a5964fba897cc98513da3ed79
