### ISSUE TITLE
Failed to install extension - extension is not packaged properly

### ISSUE THREAD

**Issue by ohadschn** [Lacro59/playnite-indiegala-plugin#6]
Getting the error in the title from Playnite when double clicking the `pext`:
![image](https://user-images.githubusercontent.com/8555641/96124350-20d04680-0efc-11eb-863b-0bbf4d5d20fc.png)

Using latest versions at the time of writing-
`Playnite: 8.1`
`playnite-indiegala-plugin: 1.0`

Relevant playnite.log excerpt:
```
15-10 15:35:54.352|INFO|PlayniteApplication:Executing command "ExtensionInstall" from pipe with arguments "F:\Downloads\IndiegalaLibrary_1_0.pext"
15-10 15:35:54.352|ERROR|ExtensionInstaller:Extension package is invalid, no extension ID found.
15-10 15:35:54.352|ERROR|PlayniteApplication:Failed to install extension.Playnite.SDK.LocalizedException: Extension is not packaged properly.
   at Playnite.Plugins.ExtensionInstaller.VerifyExtensionPackage(String packagePath) in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionInstaller.cs:line 310
   at Playnite.PlayniteApplication.InstallExtensionFile(String extensionFile) in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 1005
15-10 15:35:54.352|INFO|PlayniteApplication:Application already running, shutting down.
```

So looks like this is the issue: **_Extension package is invalid, no extension ID found_**

**Comment by Lacro59** [comment]
I posted on forum the resolved package.
https://playnite.link/forum/thread-344-post-2090.html#pid2090

**Comment by ohadschn** [comment]
Thanks! 
Why not create a GitHub release though?
Most people would prefer downloading from here, it's a reputable sire with automatic AV scans etc...

**Comment by Lacro59** [comment]
The release on Github is updated.

**Comment by Lacro59** [comment]
I created a issue: https://github.com/Lacro59/playnite-indiegala-plugin/issues/7
Can you post there your Playnite.log for investigate?
